# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e14224334453dd09d6efd65a4d2795c197352ba559fbf0cfc7fbc1c9099f75daea355388ea447fc947f20516f547e9ee775646b94e3c634f3f9f270ced1e0d0d

test:
  secret_key_base: cff1340803341461e6f9b047670aee41935c71f7f8046056ae81e25b5930ad15c4f6d485d1b02394ebe30a51bef35914ce6a9130507c9a64b66fda8f19044a73

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
